
name: Build Infrastructure on the AWS

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy infra
    runs-on: ubuntu-latest
    enviroment: prod

    steps:
    - uses: actions/checkout@v3

    - name: Setup python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: IaC deploy
      env:
        COMMAND_IAC: terraform

    - run: |
        cd infra
        $COMMAND_IAC apply -auto--aprove