
name: Test build Infrastructure on the AWS

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy infra
    runs-on: ubuntu-latest
    enviroment: prod-test

    steps:

    - uses: actions/checkout@v3

    - name: Setup python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: IaC deploy
      env:
        COMMAND_IAC: terraform


    - run: |
      cd infra
      $COMMAND_IAC init
      $COMMAND_IAC fmt
      $COMMAND_IAC validate
      $COMMAND_IAC plan
